# Generated by Django 5.2 on 2025-05-14 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='')),
                ('user', models.CharField(max_length=50, verbose_name='')),
            ],
            options={
                'verbose_name': 'Заявки',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=300)),
                ('link', models.URLField(max_length=100)),
                ('image', models.ImageField(upload_to=None)),
                ('isActive', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Игры',
                'verbose_name_plural': 'Игры',
            },
        ),
    ]
